# Generated by Django 5.2.17 on 2026-09-27 20:55

import apps.profiles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to=apps.profiles.models.avatar_upload_to)),
                ('timezone', models.CharField(default='UTC', help_text='Availability times are stored in this time zone.', max_length=64, validators=[apps.profiles.models.validate_timezone])),
                ('is_discoverable', models.BooleanField(default=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('communication_modes', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.communicationmode')),
                ('goals', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.learninggoal')),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='profiles.profile')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('native', 'Native'), ('learning', 'Learning')], max_length=10)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='languages.proficiencylevel')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_languages', to='languages.language')),
                ('self_declared_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='languages.proficiencylevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_discoverable', 'last_active_at'], name='profiles_discoverable_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='profiles_slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='profiles_slot_valid_weekday'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('profile', 'weekday', 'start_time'), name='profiles_slot_unique_start'),
        ),
        migrations.AddIndex(
            model_name='userlanguage',
            index=models.Index(fields=['language', 'role'], name='profiles_ul_language_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='userlanguage',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='profiles_userlanguage_unique_user_language'),
        ),
        migrations.AddConstraint(
            model_name='userlanguage',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'learning'), models.Q(('assessed_level__isnull', True), ('self_declared_level__isnull', True)), _connector='OR'), name='profiles_userlanguage_levels_only_when_learning'),
        ),
    ]
