# Generated by Django 5.2.17 on 2026-09-28 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlanguage',
            name='assessment_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name='userlanguage',
            constraint=models.CheckConstraint(condition=models.Q(('assessment_confidence__gte', 0), ('assessment_confidence__lte', 1)), name='profiles_userlanguage_confidence_range'),
        ),
    ]
