# Generated by Django 5.2.17 on 2026-09-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='BCP 47 tag, for example en, bn or hi.', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Name in English.', max_length=60)),
                ('native_name', models.CharField(help_text='Name in the language itself.', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProficiencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='languages_proficiency_rank_gte_1')],
            },
        ),
    ]
