# Generated by Django 5.2.17 on 2026-09-27 20:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usefulness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_practice_again', models.BooleanField()),
                ('difficulty', models.CharField(choices=[('too_easy', 'Too easy'), ('comfortable', 'Comfortable'), ('too_difficult', 'Too difficult')], max_length=15)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='exchange.exchangesession')),
            ],
            options={
                'verbose_name_plural': 'session feedback',
                'indexes': [models.Index(fields=['reviewee', '-created_at'], name='feedback_reviewee_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'reviewer'), name='feedback_one_per_reviewer_session'), models.CheckConstraint(condition=models.Q(('usefulness__gte', 1), ('usefulness__lte', 5)), name='feedback_usefulness_range'), models.CheckConstraint(condition=models.Q(('reviewer', models.F('reviewee')), _negated=True), name='feedback_not_self')],
            },
        ),
    ]
