# Generated by Django 5.2.17 on 2026-09-27 20:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('score_at_request', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_match_requests', to=settings.AUTH_USER_MODEL)),
                ('receiver_learning_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='languages.language')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_match_requests', to=settings.AUTH_USER_MODEL)),
                ('sender_learning_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='languages.language')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_a_learning_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='languages.language')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to=settings.AUTH_USER_MODEL)),
                ('user_b_learning_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='languages.language')),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='matching.matchrequest')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('breakdown', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['receiver', 'status', '-created_at'], name='matching_req_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['sender', 'status', '-created_at'], name='matching_req_outbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchrequest',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='matching_request_not_self'),
        ),
        migrations.AddConstraint(
            model_name='matchrequest',
            constraint=models.CheckConstraint(condition=models.Q(('sender_learning_language', models.F('receiver_learning_language')), _negated=True), name='matching_request_languages_differ'),
        ),
        migrations.AddConstraint(
            model_name='matchrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'receiver'), name='matching_request_one_pending'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('user_a__lt', models.F('user_b'))), name='matching_match_ordered_pair'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('user_a_learning_language', models.F('user_b_learning_language')), _negated=True), name='matching_match_languages_differ'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user_a', 'user_b'), name='matching_match_one_active'),
        ),
        migrations.AddIndex(
            model_name='matchsuggestion',
            index=models.Index(fields=['user', '-score'], name='matching_suggestion_rank_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchsuggestion',
            constraint=models.UniqueConstraint(fields=('user', 'candidate'), name='matching_suggestion_unique'),
        ),
        migrations.AddConstraint(
            model_name='matchsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('candidate')), _negated=True), name='matching_suggestion_not_self'),
        ),
        migrations.AddConstraint(
            model_name='matchsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='matching_suggestion_score_range'),
        ),
    ]
