# Generated by Django 5.2.17 on 2026-09-27 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'question categories',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('rank', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=20)),
                ('xp_reward', models.PositiveSmallIntegerField(help_text='XP for a correct answer.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='practice_difficulty_rank_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('english_meaning', models.TextField()),
                ('english_explanation', models.TextField()),
                ('source', models.CharField(choices=[('verified', 'Verified question bank'), ('ai', 'AI-generated')], default='verified', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Reviewed by a fluent speaker.')),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='practice.difficultylevel')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='languages.language')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='practice.questioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=12)),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_sessions', to='languages.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('selected_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField(null=True)),
                ('xp_awarded', models.PositiveSmallIntegerField(default=0)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='practice.difficultylevel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='practice.practicequestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='practice.practicesession')),
            ],
            options={
                'ordering': ['session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='UserCategoryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='practice.questioncategory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='languages.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('questions_answered', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('sessions_completed', models.PositiveIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='languages.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user progress',
            },
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'language', '-created_at'], name='practice_session_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='practicesession',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__gte', 1)), name='practice_session_has_questions'),
        ),
        migrations.AddConstraint(
            model_name='practicesession',
            constraint=models.CheckConstraint(condition=models.Q(('correct_count__lte', models.F('question_count'))), name='practice_session_correct_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='practicesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'language'), name='practice_session_one_in_progress'),
        ),
        migrations.AddConstraint(
            model_name='practiceanswer',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='practice_answer_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='practiceanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='practice_answer_unique_question'),
        ),
        migrations.AddConstraint(
            model_name='practiceanswer',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='practice_answer_position_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='practiceanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answered_at__isnull', True), ('is_correct__isnull', True), ('selected_option', ''), ('xp_awarded', 0)), models.Q(('answered_at__isnull', False), ('is_correct__isnull', False), models.Q(('selected_option', ''), _negated=True)), _connector='OR'), name='practice_answer_consistent_state'),
        ),
        migrations.AddIndex(
            model_name='practicequestion',
            index=models.Index(fields=['language', 'difficulty', 'is_active', 'is_verified'], name='practice_q_selection_idx'),
        ),
        migrations.AddIndex(
            model_name='practicequestion',
            index=models.Index(fields=['language', 'category'], name='practice_q_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='practicequestion',
            constraint=models.UniqueConstraint(fields=('language', 'content_hash'), name='practice_question_unique_content'),
        ),
        migrations.AddConstraint(
            model_name='practicequestion',
            constraint=models.CheckConstraint(condition=models.Q(('correct_option__in', ['A', 'B', 'C', 'D'])), name='practice_question_valid_correct_option'),
        ),
        migrations.AddConstraint(
            model_name='usercategorystat',
            constraint=models.UniqueConstraint(fields=('user', 'language', 'category'), name='practice_categorystat_unique'),
        ),
        migrations.AddConstraint(
            model_name='usercategorystat',
            constraint=models.CheckConstraint(condition=models.Q(('correct_answers__lte', models.F('questions_answered'))), name='practice_categorystat_correct_lte_answered'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='practice_progress_unique_user_language'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.CheckConstraint(condition=models.Q(('correct_answers__lte', models.F('questions_answered'))), name='practice_progress_correct_lte_answered'),
        ),
    ]
