# Generated by Django 5.2.17 on 2026-09-27 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('match_request', 'Match request'), ('match_accepted', 'Match accepted'), ('new_message', 'New message'), ('session_reminder', 'Session reminder'), ('feedback_request', 'Feedback request')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(blank=True, help_text='Site-relative path, e.g. /matches/12/.', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notifications_inbox_idx')],
            },
        ),
    ]
